data:
  root: REFUGE
  image_size: 768
model:
  name: rfau_cnxt
  encoder_name: convnext_large
  num_classes: 3
  pretrained: false
  checkpoint_path: model.safetensors
train:
  output_dir: outputs/rfau_cnxt_large_dice
  device: cuda
  epochs: 10
  batch_size: 12
  workers: 24
  lr: 0.0001
  weight_decay: 0.01
  scheduler: cosine
  loss: dice
  amp: true
eval:
  output_dir: outputs/rfau_cnxt_large_dice/predictions
