data:
  root: REFUGE
  image_size: 768
model:
  name: segformer
  model_name: nvidia/segformer-b5-finetuned-ade-640-640
  num_classes: 3
train:
  output_dir: outputs/segformer_b5_ce_dice
  device: cuda
  epochs: 80
  batch_size: 8
  workers: 8
  lr: 0.00006
  weight_decay: 0.01
  scheduler: cosine
  loss: ce_dice
  amp: true
eval:
  output_dir: outputs/segformer_b5_ce_dice/predictions
